CREATE DATABASE DB1
GO
USE DB1
GO
ALTER DATABASE DB1
SET RECOVERY SIMPLE

CREATE TABLE KHACH
(
	MAKH INT PRIMARY KEY IDENTITY(1, 1),
	TENKH NVARCHAR(50) NOT NULL,
	DIACHI NVARCHAR(MAX) NOT NULL
)

INSERT INTO KHACH (TENKH, DIACHI) VALUES
(N'Cường', N'Hóc Môn'),
(N'Hà', N'Quận 12'),
(N'Điền', N'Tân Phú')

--FULL
BACKUP DATABASE DB1 
TO DISK='..\..\Full_T2.bak'
WITH INIT

INSERT INTO KHACH (TENKH, DIACHI) VALUES
(N'Tú', N'Quận 12')

BACKUP DATABASE DB1 
TO DISK='..\..\DIFF_T3.bak'
WITH DIFFERENTIAL

INSERT INTO KHACH (TENKH, DIACHI) VALUES
(N'Tỏi', N'Hóc Môn')

BACKUP DATABASE DB1 
TO DISK='..\..\DIFF_T4.bak'
WITH DIFFERENTIAL

INSERT INTO KHACH (TENKH, DIACHI) VALUES
(N'Tuấn', N'')

BACKUP DATABASE DB1 
TO DISK='..\..\DIFF_T5.bak'
WITH DIFFERENTIAL

INSERT INTO KHACH (TENKH, DIACHI) VALUES
(N'Tín', N'Hóc Môn')

BACKUP DATABASE DB1 
TO DISK='..\..\Full_T6.bak'
WITH INIT

INSERT INTO KHACH (TENKH, DIACHI) VALUES
(N'Khoa', N'Quận 8')

BACKUP DATABASE DB1 
TO DISK='..\..\DIFF_T7.bak'
WITH DIFFERENTIAL

INSERT INTO KHACH (TENKH, DIACHI) VALUES
(N'Kiệt', N'Củ Chi')

BACKUP DATABASE DB1 
TO DISK='..\..\DIFF_CN.bak'
WITH DIFFERENTIAL

--b -> T2 - T3 - T4 - T5
RESTORE DATABASE DB1
FROM DISK = '..\..\FULL_T2.bak'
WITH NORECOVERY

RESTORE DATABASE DB1
FROM DISK = '..\..\DIFF_T3.bak'
WITH NORECOVERY

RESTORE DATABASE DB1
FROM DISK = '..\..\DIFF_T4.bak'
WITH NORECOVERY

RESTORE DATABASE DB1
FROM DISK = '..\..\DIFF_T5.bak'
WITH NORECOVERY

RESTORE DATABASE DB1 WITH RECOVERY