CREATE DATABASE QLHV 

USE QLHV

GO

ALTER DATABASE QLHV
SET RECOVERY FULL

CREATE TABLE KHOAHOC
(
	MAKH CHAR(10) PRIMARY KEY,
	TENKH NVARCHAR(50),
	THOILUONG INT
);

INSERT INTO KHOAHOC
VALUES ('KH001', N'TIENG ANH', 3);

BACKUP DATABASE QLHV
TO DISK = '..\..\FULLQLHV.BAK'

INSERT INTO KHOAHOC
VALUES ('KH002', N'TIENG TRUNG', 6);

BACKUP DATABASE QLHV
TO DISK = '..\..\DIFFQLHV.BAK'
WITH DIFFERENTIAL

INSERT INTO KHOAHOC
VALUES ('KH003', N'TIẾNG HÀN', 12);

BACKUP LOG QLHV
TO DISK = '..\..\LOGQLHV.BAK'

INSERT INTO KHOAHOC
VALUES ('KH004', N'TIẾNG NHẬT', 6);

BACKUP LOG QLHV
TO DISK = '..\..\LOGQLHV.BAK'

SELECT * FROM KHOAHOC;

-- 

RESTORE DATABASE QLHV
FROM DISK = '..\..\FULLQLHV.BAK'
WITH NORECOVERY; 

RESTORE DATABASE QLHV
FROM DISK = '..\..\DIFFQLHV.BAK'
WITH NORECOVERY; 

RESTORE LOG QLHV
FROM DISK = '..\..\LOGQLHV.BAK'
WITH NORECOVERY; 

RESTORE DATABASE QLHV
WITH RECOVERY; 

