CREATE DATABASE QLBH
GO
USE QLBH
GO
ALTER DATABASE QLBH
SET RECOVERY FULL

CREATE TABLE HOADON
(
	MAHD INT PRIMARY KEY IDENTITY(1, 1),
	TOTALPRICE MONEY NOT NULL
)

INSERT INTO HOADON (TOTALPRICE) VALUES
(1000),
(2000),
(3000)

BACKUP DATABASE QLBH
TO DISK = '..\..\T1.bak'
WITH INIT

INSERT INTO HOADON (TOTALPRICE) VALUES
(1000)

BACKUP LOG QLBH
TO DISK = '..\..\T2.trn'

INSERT INTO HOADON (TOTALPRICE) VALUES
(2000)

BACKUP DATABASE QLBH
TO DISK = '..\..\T3.bak'
WITH DIFFERENTIAL

BACKUP LOG QLBH
TO DISK = '..\..\T4.trn'

RESTORE DATABASE QLBH
FROM DISK = '..\..\T1.bak'
WITH NORECOVERY

RESTORE DATABASE QLBH
FROM DISK = '..\..\T2.trn'
WITH NORECOVERY

RESTORE DATABASE QLBH
FROM DISK = '..\..\T3.bak'
WITH NORECOVERY

RESTORE DATABASE QLBH
FROM DISK = '..\..\T4.trn'
WITH NORECOVERY

RESTORE DATABASE QLBH WITH RECOVERY